# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:18-alpine

# Install MCP from npm
RUN npm install -g package-registry-mcp

WORKDIR /app

# Entrypoint
CMD ["package-registry-mcp"]
